CUDA_VISIBLE_DEVICES=0 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_0_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_0_pruned_model --train-batch 64 --class-index 0 &
CUDA_VISIBLE_DEVICES=1 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_1_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_1_pruned_model --train-batch 64 --class-index 1 &
CUDA_VISIBLE_DEVICES=2 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_2_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_2_pruned_model --train-batch 64 --class-index 2 &
CUDA_VISIBLE_DEVICES=3 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_3_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_3_pruned_model --train-batch 64 --class-index 3 &
CUDA_VISIBLE_DEVICES=0 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_4_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_4_pruned_model --train-batch 64 --class-index 4 &
CUDA_VISIBLE_DEVICES=1 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_5_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_5_pruned_model --train-batch 64 --class-index 5 &
CUDA_VISIBLE_DEVICES=2 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_6_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_6_pruned_model --train-batch 64 --class-index 6 &
CUDA_VISIBLE_DEVICES=3 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_7_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_7_pruned_model --train-batch 64 --class-index 7 &
CUDA_VISIBLE_DEVICES=0 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_8_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_8_pruned_model --train-batch 64 --class-index 8 &
CUDA_VISIBLE_DEVICES=1 python3 cifar_binary.py --pruned -a vgg19_bn --epochs 41 --schedule 20 30 --gamma 0.1 --resume ./apoz_pruned_models/vgg19_bn/vgg19_bn_9_pruned_model.pth --checkpoint ./apoz_pruned_retrain/vgg19_bn/vgg19_bn_9_pruned_model --train-batch 64 --class-index 9 &
wait
